
services:
  postgres:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=madness_data
    ports:
      - 5432:5432
    networks:
      - shared-network
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - shared-network
    depends_on:
      - postgres
    ports:
      - "5001:5000"  # Adjust this if needed

  website:
    container_name: madness_mult
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile  # This should be in the root directory
    ports:
      - 3000:80
    networks:
      - shared-network
    depends_on:
      - postgres

networks:
  shared-network:
